# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8yH62uqmdaBl8k6rjwofK5zduN7GAhv
"""

streamlit

pandas

numpy

matplotlib

scikit-learn

statsmodels

openpyxl